# Generated by Django 4.1 on 2022-11-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
