# Generated by Django 4.1 on 2022-12-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_accountmodel_regime_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='country',
            field=models.CharField(choices=[('MX', 'México')], max_length=10),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='state',
            field=models.CharField(choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('COAH', 'Coahuila de Zaragoza'), ('COL', 'Colima'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('DF', 'Distrito Federal'), ('DGO', 'Durango'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'Estado de México'), ('MICH', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Querétaro'), ('QR', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=10),
        ),
    ]
