# Generated by Django 4.1.2 on 2022-12-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_accountmodel_country_alter_accountmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='image_profile',
            field=models.ImageField(blank=True, default='image/img-quadrum.jpeg', null=True, upload_to='image/'),
        ),
    ]
