# Generated by Django 4.1 on 2022-11-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_alter_accountmodel_image_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
