# Generated by Django 4.1 on 2022-11-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountModel',
        ),
    ]
