# Generated by Django 4.1 on 2022-11-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_remove_accountmodel_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
