# Generated by Django 4.1.2 on 2022-12-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=3)),
                ('series', models.CharField(max_length=255, null=True)),
                ('folio', models.CharField(max_length=40, null=True)),
                ('date', models.CharField(max_length=20)),
                ('stamp', models.TextField()),
                ('payment_form', models.CharField(max_length=2, null=True)),
                ('no_certificate', models.CharField(max_length=20)),
                ('certificate', models.TextField()),
                ('payment_conditions', models.TextField(null=True)),
                ('rfc_business', models.CharField(max_length=25)),
                ('name_business', models.CharField(max_length=255)),
                ('rfc_receiver', models.CharField(max_length=25)),
                ('name_receiver', models.CharField(max_length=255)),
                ('subtotal', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('exchange_rate', models.CharField(blank=True, max_length=3)),
                ('total', models.CharField(max_length=255)),
                ('voucher_type', models.CharField(max_length=1)),
                ('export', models.CharField(max_length=2)),
                ('place_of_expedition', models.CharField(max_length=6)),
                ('metodo_pago', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidateResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=255)),
                ('voucher_type', models.CharField(max_length=25)),
                ('version', models.CharField(max_length=3)),
                ('rfc_business', models.CharField(max_length=25)),
                ('rfc_receiver', models.CharField(max_length=25)),
                ('subtotal', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('metodo_pago', models.CharField(max_length=3, null=True)),
                ('place_of_expedition', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=20)),
                ('validate_date', models.DateTimeField(auto_now=True)),
                ('estruc', models.CharField(max_length=255, null=True)),
                ('stamp', models.BooleanField(max_length=25, null=True)),
                ('stamp_sat', models.BooleanField(max_length=25, null=True)),
                ('error_ws', models.TextField(null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='validate.invoicemodel')),
            ],
        ),
    ]
