# Generated by Django 4.1.2 on 2022-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateresultmodel',
            name='stamp',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='stamp_sat',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
