# Generated by Django 4.1 on 2022-10-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0002_invoicemodel_validateresultmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='name_buiness',
            new_name='name_business',
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='exchange_rate',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
