# Generated by Django 4.1 on 2022-11-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0003_rename_name_buiness_invoicemodel_name_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validateresultmodel',
            name='error_ws',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='validateresultmodel',
            name='estruc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='validateresultmodel',
            name='stamp_sat',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='stamp',
            field=models.BooleanField(null=True),
        ),
    ]
