# Generated by Django 4.1 on 2022-12-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0003_remove_validateresultmodel_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateresultmodel',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='metodo_pago',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='place_of_expedition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='rfc_business',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='rfc_receiver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='stamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='stamp_sat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='version',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='validateresultmodel',
            name='voucher_type',
            field=models.CharField(max_length=255),
        ),
    ]
