# Generated by Django 4.1 on 2022-11-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0004_validateresultmodel_error_ws_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateresultmodel',
            name='estruc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
