# Generated by Django 4.1 on 2022-11-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validate', '0005_alter_validateresultmodel_estruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validateresultmodel',
            name='estruc',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
